on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.0"

      - name: Build app
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Build and Push Docker image'
        run: |
          gcloud builds submit --tag ${{ secrets.GCP_REGION_PROJECT_ID }}/notely:latest .
      - name: 'Deploy to Cloud Run'
        run: gcloud run deploy notely --image europe-north1-docker.pkg.dev/notely-502113/notely-ar-repo/notely:latest --region europe-north1 --allow-unauthenticated --project notely-502113 --max-instances=4
